baseurl = "http://absurdolytics/"
languageCode = "es"
title = "absurdolytics"
theme = "steam"
# disqusShortname = "spf13"
paginate = 10

[params]

	title = "absurdolytics"
	subtitle = "Samuel Vargas - svargas@contextual.team </a>"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "green"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Samuel Vargas"
	bio = "Samuel Vargas - CEO de <a href='http://contextual.team'>{ contextual }</a>"
	description = "Analítica, Aprendizaje automático y Estadísticas absurdas"
	location = "" # optional
	twitter = "_samuelvargas" # optional
    linkedin = "in/samuelvargas"
	# github = "spf13" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	# comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Seguir Leyendo"
	backtotopStr = "Inicio"
	shareStr = "Compartir"
	pageNotFoundTitle = "404 - Página no encontrada"
